version: '3.8'

services:
  postgres:
    container_name: city_country_postgres
    image: 'postgres:16.0'
    environment:
      - POSTGRES_DB=city_country_postgres
      - POSTGRES_USER=city_country_user
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5436:5432'