version: '3.8'

networks:
  citycountryemailsender_city-country-net:
    external: true

services:
  postgres:
    image: 'postgres:16.0'
    restart: always
    environment:
      - POSTGRES_DB=city_country_postgres
      - POSTGRES_USER=city_country_user
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5436:5432'
    volumes:
      - ./src/main/resources/db/changelog/changes/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/db/changelog/changes/populateCountries.sql:/docker-entrypoint-initdb.d/populateCountries.sql
    networks:
      - citycountryemailsender_city-country-net
    mem_limit: 1g

  spring-boot-app:
    container_name: city_country_spring_boot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/city_country_postgres
    networks:
      - citycountryemailsender_city-country-net
    mem_limit: 1g